# Generated by Django 5.0.6 on 2024-06-11 23:32

import app_Concessionaria.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('carro_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('carro_marca', models.CharField(max_length=60)),
                ('carro_modelo', models.CharField(max_length=120)),
                ('carro_ano', models.IntegerField()),
                ('carro_cor', models.CharField(max_length=30)),
                ('carro_status', models.CharField(choices=[('V', 'Velho'), ('N', 'Novo'), ('U', 'Usado')], max_length=1)),
                ('carro_foto', models.ImageField(blank=True, upload_to=app_Concessionaria.models.upload_foto_carro)),
            ],
            options={
                'verbose_name_plural': 'Carros',
            },
        ),
    ]
