# Generated by Django 5.0.6 on 2024-06-11 23:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Concessionaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='carro_cadastro_em',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
