# Generated by Django 5.0.6 on 2024-06-17 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Concessionaria', '0002_carro_carro_cadastro_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='carro_valor',
            field=models.FloatField(default=7, max_length=20),
            preserve_default=False,
        ),
    ]
