# Generated by Django 5.0.6 on 2024-06-17 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Concessionaria', '0003_carro_carro_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='carro_valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
