# Generated by Django 5.0.6 on 2024-06-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Concessionaria', '0004_alter_carro_carro_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='carro_cambio',
            field=models.CharField(choices=[('M', 'Manual'), ('A', 'Automático'), ('S', 'Semi-automático')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carro',
            name='carro_cidade',
            field=models.CharField(default='Gravataí', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carro',
            name='carro_combustivel',
            field=models.CharField(choices=[('G', 'Gasolina'), ('A', 'Álcool'), ('D', 'Diesel'), ('F', 'Flex'), ('E', 'Elétrico'), ('H', 'Híbrido')], default='G', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carro',
            name='carro_km',
            field=models.PositiveIntegerField(default=20),
            preserve_default=False,
        ),
    ]
